### ISSUE TITLE
Descriptions are a mess

### ISSUE THREAD

**Issue by cathal-c** [brogand93/index-replicate#8]
The CLI's short description is longer than its long description.

https://github.com/brogand93/index-replicate/blob/main/cmd/root.go#L15

This is unusable in its current form.

**Comment by brogand93** [comment]
Hi @CathalC2011, I don't personally use this any more. If you're like you're welcome to open a pull request. 

Maybe this would be a good opportunity for you to get your feet wet with open source contributions/coding in general 😄

**Comment by lauraaraviciute** [comment]
Agree with Cathal - we have mission critical systems depending on this software. We would greatly appreciate an update to the cli description thank you.
